from PyQt6.QtWidgets import (
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QGridLayout,
    QLabel,
    QPushButton,
    QCheckBox,
    QListWidget,
    QComboBox,
    QTextEdit,
    QTableWidget,
    QHeaderView,
    QTableWidgetItem,
    QSizePolicy,
)
from PyQt6.QtCore import Qt
from .components import AspectRatioBox
from .helpers.style_helper import set_panel_role
from .helpers import widget_factory


class ImageViewMixin:
    def _build_image_workspace_page(self) -> QWidget:
        page = QWidget()
        set_panel_role(page, "center")
        root = QVBoxLayout(page)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(10)
        header = QWidget()
        header_layout = QVBoxLayout(header)
        header_layout.setContentsMargins(0, 0, 0, 0)
        header_layout.setSpacing(2)
        title = QLabel("Image")
        self._set_label_role(title, "sectionTitle")
        header_layout.addWidget(title)
        subtitle = QLabel("Generate background + thumbnail images from selected samples and prompts. Configuration lives in Settings.")
        subtitle.setWordWrap(True)
        self._set_label_role(subtitle, "statusMuted")
        header_layout.addWidget(subtitle)
        root.addWidget(header)
        bg_card, bg_body = widget_factory.make_panel_section("Background Samples", self.ui, subtitle_text="Select up to 5 background samples.", soft=False)
        bg_card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        bg_meta_row = QHBoxLayout()
        bg_meta_row.setContentsMargins(0, 0, 0, 0)
        bg_meta_row.setSpacing(6)
        self.image_bg_samples_folder_label = QLabel("")
        self._set_label_role(self.image_bg_samples_folder_label, "statusMuted")
        self.image_bg_samples_folder_label.setWordWrap(True)
        bg_meta_row.addWidget(self.image_bg_samples_folder_label, 1)
        self.image_bg_random_checkbox = QCheckBox("Random")
        self.image_bg_random_checkbox.setChecked(False)
        self.image_bg_random_checkbox.toggled.connect(self._on_image_bg_random_toggled)
        bg_meta_row.addWidget(self.image_bg_random_checkbox)
        bg_open = QPushButton("Open")
        self._set_button_role(bg_open, "secondary")
        bg_open.setFixedHeight(26)
        bg_open.clicked.connect(self._on_image_open_bg_samples_dir)
        bg_meta_row.addWidget(bg_open)
        bg_refresh = QPushButton("Refresh")
        self._set_button_role(bg_refresh, "secondary")
        bg_refresh.setFixedHeight(26)
        bg_refresh.clicked.connect(lambda: self._refresh_image_ui(force=True))
        bg_meta_row.addWidget(bg_refresh)
        bg_body.addLayout(bg_meta_row)
        self.image_bg_samples_empty_label = QLabel("No background sample images found")
        self._set_label_role(self.image_bg_samples_empty_label, "statusMuted")
        self.image_bg_samples_empty_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.image_bg_samples_empty_label.setVisible(False)
        bg_body.addWidget(self.image_bg_samples_empty_label)
        self.image_bg_samples_list = QListWidget()
        self._apply_card_field(self.image_bg_samples_list)
        self.image_bg_samples_list.setSelectionMode(QListWidget.SelectionMode.MultiSelection)
        self.image_bg_samples_list.itemSelectionChanged.connect(lambda: self._on_image_bg_selection_changed())
        self.image_bg_samples_list.itemDoubleClicked.connect(self._on_image_bg_sample_double_clicked)
        bg_body.addWidget(self.image_bg_samples_list, 1)
        thumb_card, thumb_body = widget_factory.make_panel_section("Thumbnail Samples", self.ui, subtitle_text="Select up to 5 thumbnail style samples.", soft=False)
        thumb_card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        thumb_meta_row = QHBoxLayout()
        thumb_meta_row.setContentsMargins(0, 0, 0, 0)
        thumb_meta_row.setSpacing(6)
        self.image_thumb_samples_folder_label = QLabel("")
        self._set_label_role(self.image_thumb_samples_folder_label, "statusMuted")
        self.image_thumb_samples_folder_label.setWordWrap(True)
        thumb_meta_row.addWidget(self.image_thumb_samples_folder_label, 1)
        self.image_thumb_random_checkbox = QCheckBox("Random")
        self.image_thumb_random_checkbox.setChecked(False)
        self.image_thumb_random_checkbox.toggled.connect(self._on_image_thumb_random_toggled)
        thumb_meta_row.addWidget(self.image_thumb_random_checkbox)
        thumb_text_presets = QPushButton("Text Presets")
        self._set_button_role(thumb_text_presets, "secondary")
        thumb_text_presets.setFixedHeight(26)
        thumb_text_presets.clicked.connect(self._on_image_text_presets_clicked)
        thumb_meta_row.addWidget(thumb_text_presets)
        thumb_open = QPushButton("Open")
        self._set_button_role(thumb_open, "secondary")
        thumb_open.setFixedHeight(26)
        thumb_open.clicked.connect(self._on_image_open_thumb_samples_dir)
        thumb_meta_row.addWidget(thumb_open)
        thumb_refresh = QPushButton("Refresh")
        self._set_button_role(thumb_refresh, "secondary")
        thumb_refresh.setFixedHeight(26)
        thumb_refresh.clicked.connect(lambda: self._refresh_image_ui(force=True))
        thumb_meta_row.addWidget(thumb_refresh)
        thumb_body.addLayout(thumb_meta_row)
        self.image_thumb_samples_empty_label = QLabel("No thumbnail sample images found")
        self._set_label_role(self.image_thumb_samples_empty_label, "statusMuted")
        self.image_thumb_samples_empty_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.image_thumb_samples_empty_label.setVisible(False)
        thumb_body.addWidget(self.image_thumb_samples_empty_label)
        self.image_thumb_samples_list = QListWidget()
        self._apply_card_field(self.image_thumb_samples_list)
        self.image_thumb_samples_list.setSelectionMode(QListWidget.SelectionMode.MultiSelection)
        self.image_thumb_samples_list.itemSelectionChanged.connect(lambda: self._on_image_thumb_selection_changed())
        self.image_thumb_samples_list.itemDoubleClicked.connect(self._on_image_thumb_sample_double_clicked)
        thumb_body.addWidget(self.image_thumb_samples_list, 1)
        res_text = ""
        try:
            settings = self._music_settings()
            res_text = str(settings.get("outputResolution", "")).strip() or str(settings.get("imageResolution", "")).strip()
        except Exception:
            res_text = ""
        rw, rh = (16, 9)
        try:
            if hasattr(self, "_parse_output_resolution"):
                rw, rh = self._parse_output_resolution(res_text)
        except Exception:
            rw, rh = (16, 9)
        bg_preview_card, bg_preview_body = widget_factory.make_panel_section("Background Preview", self.ui, subtitle_text="Preview selected or generated background image.", soft=False)
        bg_preview_card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.image_bg_preview = QLabel("Select a job from Job Queue to preview")
        self.image_bg_preview.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._set_label_role(self.image_bg_preview, "statusMuted")
        self.image_bg_preview_box = AspectRatioBox(self.image_bg_preview, int(rw), int(rh))
        self.image_bg_preview_box.setMinimumHeight(140)
        bg_preview_body.addWidget(self.image_bg_preview_box)
        thumb_preview_card, thumb_preview_body = widget_factory.make_panel_section("Thumbnail Preview", self.ui, subtitle_text="Preview selected or generated thumbnail image.", soft=False)
        thumb_preview_card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.image_thumb_preview = QLabel("Select a job from Job Queue to preview")
        self.image_thumb_preview.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._set_label_role(self.image_thumb_preview, "statusMuted")
        self.image_thumb_preview_box = AspectRatioBox(self.image_thumb_preview, int(rw), int(rh))
        self.image_thumb_preview_box.setMinimumHeight(140)
        thumb_preview_body.addWidget(self.image_thumb_preview_box)
        prompt_card, prompt_body = widget_factory.make_panel_section("Prompt + Run", self.ui, subtitle_text="Pick a prompt and generate jobs for the selected date range.", soft=False)
        prompt_card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        preset_row = QHBoxLayout()
        preset_row.setContentsMargins(0, 0, 0, 0)
        preset_row.setSpacing(8)
        self.image_prompt_preset_combo = QComboBox()
        self._apply_card_field(self.image_prompt_preset_combo)
        self.image_prompt_preset_combo.currentIndexChanged.connect(lambda _: self._on_image_prompt_preset_selected())
        preset_row.addWidget(self.image_prompt_preset_combo, 1)
        manage_btn = QPushButton("Manage")
        self._set_button_role(manage_btn, "secondary")
        manage_btn.setFixedHeight(28)
        manage_btn.clicked.connect(self._on_image_manage_prompts_clicked)
        preset_row.addWidget(manage_btn)
        pick_btn = QPushButton("Pick Random")
        self._set_button_role(pick_btn, "secondary")
        pick_btn.setFixedHeight(28)
        pick_btn.clicked.connect(self._on_image_pick_prompt_clicked)
        preset_row.addWidget(pick_btn)
        prompt_body.addLayout(preset_row)
        self.image_prompt_editor = QTextEdit()
        self.image_prompt_editor.setMinimumHeight(90)
        self._set_field_role(self.image_prompt_editor, "card")
        self.image_prompt_editor.textChanged.connect(lambda: self._on_image_prompt_changed())
        prompt_body.addWidget(self.image_prompt_editor, 1)
        self.image_status_label = QLabel("Ready")
        self._set_label_role(self.image_status_label, "statusMuted")
        self.image_status_label.setWordWrap(True)
        prompt_body.addWidget(self.image_status_label)
        batches_card, batches_body = widget_factory.make_panel_section("Batches", self.ui, subtitle_text="Choose batches and enqueue background + thumbnail jobs.", soft=False)
        date_row = QHBoxLayout()
        date_row.setContentsMargins(0, 0, 0, 0)
        date_row.setSpacing(6)
        from_lab = QLabel("From")
        self._set_label_role(from_lab, "metricTitle")
        date_row.addWidget(from_lab)
        self.image_from_input = widget_factory.create_calendar_picker(lambda: self._on_image_date_changed(), self.ui, width=104)
        date_row.addWidget(self.image_from_input)
        to_lab = QLabel("To")
        self._set_label_role(to_lab, "metricTitle")
        date_row.addWidget(to_lab)
        self.image_to_input = widget_factory.create_calendar_picker(lambda: self._on_image_date_changed(), self.ui, width=104)
        date_row.addWidget(self.image_to_input)
        date_row.addStretch(1)
        batches_body.addLayout(date_row)
        batches_row = QHBoxLayout()
        batches_row.setContentsMargins(0, 0, 0, 0)
        batches_row.setSpacing(6)
        batches_lab = QLabel("Batches")
        self._set_label_role(batches_lab, "metricTitle")
        batches_row.addWidget(batches_lab)
        self.image_batches_selected_label = QLabel("")
        self._set_label_role(self.image_batches_selected_label, "statusMuted")
        batches_row.addWidget(self.image_batches_selected_label)
        batches_row.addStretch(1)
        batches_refresh = QPushButton("Reload")
        self._set_button_role(batches_refresh, "secondary")
        batches_refresh.setFixedHeight(26)
        batches_refresh.clicked.connect(lambda: self._refresh_image_ui(force=True))
        batches_row.addWidget(batches_refresh)
        batches_body.addLayout(batches_row)
        self.image_batches_list = QListWidget()
        self._apply_card_field(self.image_batches_list)
        self.image_batches_list.setSelectionMode(QListWidget.SelectionMode.MultiSelection)
        self.image_batches_list.setMinimumHeight(110)
        self.image_batches_list.itemSelectionChanged.connect(self._on_image_batches_selection_changed)
        batches_body.addWidget(self.image_batches_list, 1)
        action_row = QHBoxLayout()
        action_row.setContentsMargins(0, 0, 0, 0)
        action_row.setSpacing(8)
        self.image_generate_now_button = QPushButton("Generate Now")
        self._set_button_role(self.image_generate_now_button, "primary")
        self.image_generate_now_button.setFixedHeight(30)
        self.image_generate_now_button.clicked.connect(self._on_image_generate_now_clicked)
        action_row.addWidget(self.image_generate_now_button)
        self.image_stop_button = QPushButton("Stop")
        self._set_button_role(self.image_stop_button, "warning")
        self.image_stop_button.setFixedHeight(30)
        self.image_stop_button.setEnabled(False)
        self.image_stop_button.clicked.connect(self._on_image_stop_clicked)
        action_row.addWidget(self.image_stop_button)
        self.image_clear_queue_button = QPushButton("Clear Queue")
        self._set_button_role(self.image_clear_queue_button, "danger")
        self.image_clear_queue_button.setFixedHeight(30)
        self.image_clear_queue_button.clicked.connect(self._on_image_clear_queue_clicked)
        action_row.addWidget(self.image_clear_queue_button)
        self.image_gen_thumbs_button = QPushButton("Generate Thumbnails")
        self._set_button_role(self.image_gen_thumbs_button, "primary")
        self.image_gen_thumbs_button.setFixedHeight(30)
        self.image_gen_thumbs_button.clicked.connect(self._on_image_generate_thumbnails_clicked)
        action_row.addWidget(self.image_gen_thumbs_button)
        action_row.addStretch(1)
        batches_body.addLayout(action_row)
        jobs_card, jobs_body = widget_factory.make_panel_section("Job Queue", self.ui, subtitle_text="One row per channel per batch (background + thumbnail).", soft=False)
        self.image_jobs_empty_label = QLabel("No jobs yet — click Generate Now")
        self._set_label_role(self.image_jobs_empty_label, "statusMuted")
        self.image_jobs_empty_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.image_jobs_empty_label.setVisible(False)
        jobs_body.addWidget(self.image_jobs_empty_label)
        self.image_jobs_status_label = QLabel("")
        self._set_label_role(self.image_jobs_status_label, "statusMuted")
        self.image_jobs_status_label.setWordWrap(True)
        jobs_body.addWidget(self.image_jobs_status_label)
        self.image_jobs_table = QTableWidget(0, 7)
        self.image_jobs_table.setHorizontalHeaderLabels(["Batch", "Channel", "Role", "BG", "TH", "BG File", "TH File"])
        self.image_jobs_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.image_jobs_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
        self.image_jobs_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.image_jobs_table.verticalHeader().setVisible(False)
        self.image_jobs_table.verticalHeader().setDefaultSectionSize(34)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Interactive)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
        self.image_jobs_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Stretch)
        self.image_jobs_table.setColumnWidth(1, 220)
        self.image_jobs_table.itemSelectionChanged.connect(self._on_image_job_selected)
        self.image_jobs_table.cellDoubleClicked.connect(self._on_image_job_double_clicked)
        self._apply_card_field(self.image_jobs_table)
        jobs_body.addWidget(self.image_jobs_table, 1)
        self.image_footer_detail = QLabel("")
        self._set_label_role(self.image_footer_detail, "statusMuted")
        self.image_footer_detail.setWordWrap(True)
        self.image_footer_detail.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        jobs_body.addWidget(self.image_footer_detail)
        main_row = QHBoxLayout()
        main_row.setContentsMargins(0, 0, 0, 0)
        main_row.setSpacing(10)

        left = QWidget()
        left_layout = QVBoxLayout(left)
        left_layout.setContentsMargins(0, 0, 0, 0)
        left_layout.setSpacing(10)

        top_grid = QGridLayout()
        top_grid.setContentsMargins(0, 0, 0, 0)
        top_grid.setHorizontalSpacing(10)
        top_grid.setVerticalSpacing(10)
        top_grid.addWidget(bg_card, 0, 0)
        top_grid.addWidget(bg_preview_card, 0, 1)
        top_grid.addWidget(thumb_card, 1, 0)
        top_grid.addWidget(thumb_preview_card, 1, 1)
        top_grid.setColumnStretch(0, 4)
        top_grid.setColumnStretch(1, 5)
        top_grid.setRowStretch(0, 1)
        top_grid.setRowStretch(1, 1)
        left_layout.addLayout(top_grid, 2)
        left_layout.addWidget(prompt_card, 1)

        right = QWidget()
        right_layout = QVBoxLayout(right)
        right_layout.setContentsMargins(0, 0, 0, 0)
        right_layout.setSpacing(10)
        right_layout.addWidget(batches_card)
        right_layout.addWidget(jobs_card, 1)

        main_row.addWidget(left, 1)
        main_row.addWidget(right, 1)
        root.addLayout(main_row, 1)
        return page
