
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QSlider, QLabel, QPushButton,
    QFileDialog, QLineEdit, QComboBox, QProgressBar, QColorDialog,
    QScrollArea, QCheckBox, QMessageBox, QTabWidget, QListWidget,
    QListWidgetItem, QStackedWidget, QToolButton, QTextEdit, QSpinBox,
    QTableWidget, QTableWidgetItem, QHeaderView, QDateEdit, QSizePolicy
)
from PyQt6.QtCore import Qt, QSize
from PyQt6.QtGui import QIcon, QColor

from .helpers.style_helper import set_panel_role
from .helpers import widget_factory

class SettingsViewMixin:
    def _build_settings_scroll_page(self, title_text: str, subtitle_text: str='', *, max_width: int=1240) -> tuple[QWidget, QVBoxLayout]:
        page = QWidget()
        root = QVBoxLayout(page)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        root.addWidget(scroll, 1)
        content = QWidget()
        scroll.setWidget(content)
        content_layout = QVBoxLayout(content)
        content_layout.setContentsMargins(8, 8, 18, 18)
        content_layout.setSpacing(14)
        header = QWidget()
        header_layout = QVBoxLayout(header)
        header_layout.setContentsMargins(2, 0, 2, 2)
        header_layout.setSpacing(2)
        title = QLabel(title_text)
        self._set_label_role(title, 'sectionTitle')
        header_layout.addWidget(title)
        if subtitle_text:
            subtitle = QLabel(subtitle_text)
            self._set_label_role(subtitle, 'statusMuted')
            subtitle.setWordWrap(True)
            header_layout.addWidget(subtitle)
        content_layout.addWidget(header)
        return (page, content_layout)

    def _build_settings_ui(self, left_panel: QVBoxLayout):
    
        def tab_body() -> tuple[QWidget, QVBoxLayout]:
            page = QWidget()
            page_layout = QVBoxLayout(page)
            page_layout.setContentsMargins(0, 6, 0, 0)
            page_layout.setSpacing(6)
            return (page, page_layout)
    
        def section_card(layout: QVBoxLayout, title: str, subtitle: str='') -> QVBoxLayout:
            card, body = widget_factory.make_panel_section(title, self.ui, subtitle_text=subtitle, soft=False)
            layout.addWidget(card)
            return body
    
        def subheading(layout: QVBoxLayout, text: str):
            lab = QLabel(text)
            self._set_label_role(lab, 'subheading')
            layout.addWidget(lab)
        tabs = QTabWidget()
        tabs.setDocumentMode(True)
        tabs.setElideMode(Qt.TextElideMode.ElideRight)
        tabs.setUsesScrollButtons(False)
        set_panel_role(tabs, "compactTabsSmall")
        spectrum_page, spectrum_layout = tab_body()
        preset_layout = section_card(spectrum_layout, 'Spectrum', 'Presets and stacked ring setup.')
        self.spectrum_enabled = widget_factory.add_toggle_row(preset_layout, 'Enable Spectrum', self._video_controller.update_spectrum_enabled, self.ui)
        preset_layout.addWidget(QLabel('Style Preset'))
        self.style_combo = QComboBox()
        self._apply_card_field(self.style_combo)
        styles = [('classic-vertical', 'Classic Vertical Bars'), ('thin-lines', 'Thin Frequency Lines'), ('dot-matrix', 'Dot Matrix Bars'), ('symmetrical-bars', 'Symmetrical Bars'), ('soft-waveform', 'Continuous Waveform'), ('mountain', 'Filled Mountain'), ('liquid', 'Liquid Plasma'), ('pixel-bars', 'Pixel Bars'), ('neon-pulse', 'Neon Pulse Bars'), ('floating-blocks', 'Floating Blocks')]
        for v, label in styles:
            self.style_combo.addItem(label, userData=v)
        self.style_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_style())
        preset_layout.addWidget(self.style_combo)
        preset_layout.addWidget(QLabel('Stacked Ring Preset'))
        stack_row = QHBoxLayout()
        stack_row.setContentsMargins(0, 0, 0, 0)
        stack_row.setSpacing(4)
        self.stack_preset_combo = QComboBox()
        self._apply_card_field(self.stack_preset_combo)
        self.stack_preset_combo.addItem('Pick stacked preset...', userData='')
        self.stack_preset_combo.addItem('Triple Neon Halo', userData='triple-neon-halo')
        self.stack_preset_combo.addItem('Bass Vortex Stack', userData='bass-vortex-stack')
        self.stack_preset_combo.addItem('Soft Aura Stack', userData='soft-aura-stack')
        stack_row.addWidget(self.stack_preset_combo, 1)
        self.btn_apply_stack_preset = QPushButton('Apply')
        self._set_button_role(self.btn_apply_stack_preset, 'primary')
        self.btn_apply_stack_preset.clicked.connect(self._apply_stacked_preset)
        stack_row.addWidget(self.btn_apply_stack_preset)
        self.btn_clear_stack_preset = QPushButton('Clear')
        self._set_button_role(self.btn_clear_stack_preset, 'compactSecondary')
        self.btn_clear_stack_preset.clicked.connect(self._clear_stacked_preset)
        stack_row.addWidget(self.btn_clear_stack_preset)
        preset_layout.addLayout(stack_row)
        audio_layout = section_card(spectrum_layout, 'Audio Reactivity', 'Global spectrum response before per-element motion tuning.')
        self.sens_label, self.sens_slider = widget_factory.add_slider_row(audio_layout, 'Sensitivity (1.00)', 0, 200, 100, self._video_controller.update_audio_sensitivity, self.ui)
        self.smooth_label, self.smooth_slider = widget_factory.add_slider_row(audio_layout, 'Smoothing (0.80)', 0, 99, 80, self._video_controller.update_audio_smoothing, self.ui)
        position_layout = section_card(spectrum_layout, 'Positioning', 'Move the spectrum and logo anchor around the preview.')
        row = QHBoxLayout()
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(6)
        lab = QLabel('Spectrum Position')
        self._set_label_role(lab, 'subheading')
        row.addWidget(lab)
        row.addStretch()
        btn = QPushButton('Reset Center')
        self._set_button_role(btn, 'compactSecondary')
        btn.clicked.connect(self._video_controller.reset_center)
        row.addWidget(btn)
        position_layout.addLayout(row)
        self.anchor_combo = QComboBox()
        anchors = [('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('center', 'Center'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')]
        for v, label in anchors:
            self.anchor_combo.addItem(label, userData=v)
        self.anchor_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_anchor())
        widget_factory.add_form_row(position_layout, 'Anchor', self.anchor_combo, self.ui, apply_card_field=True)
        xy_row = QHBoxLayout()
        xy_row.setContentsMargins(0, 0, 0, 0)
        xy_row.setSpacing(4)
        xw = QWidget()
        xl = QVBoxLayout(xw)
        xl.setContentsMargins(0, 0, 0, 0)
        xl.setSpacing(3)
        x_header, self.x_label = widget_factory.create_metric_header('X Offset (0)', self.ui)
        xl.addLayout(x_header)
        self.x_slider = QSlider(Qt.Orientation.Horizontal)
        self.x_slider.setMinimum(-1000)
        self.x_slider.setMaximum(1000)
        self.x_slider.setValue(0)
        self.x_slider.valueChanged.connect(lambda v: self._video_controller.update_pos_x(v))
        xl.addWidget(self.x_slider)
        xy_row.addWidget(xw, 1)
        yw = QWidget()
        yl = QVBoxLayout(yw)
        yl.setContentsMargins(0, 0, 0, 0)
        yl.setSpacing(3)
        y_header, self.y_label = widget_factory.create_metric_header('Y Offset (0)', self.ui)
        yl.addLayout(y_header)
        self.y_slider = QSlider(Qt.Orientation.Horizontal)
        self.y_slider.setMinimum(-1000)
        self.y_slider.setMaximum(1000)
        self.y_slider.setValue(0)
        self.y_slider.valueChanged.connect(lambda v: self._video_controller.update_pos_y(v))
        yl.addWidget(self.y_slider)
        xy_row.addWidget(yw, 1)
        position_layout.addLayout(xy_row)
        spectrum_layout.addStretch(1)
        background_page, bg_layout = tab_body()
        bg_card = section_card(bg_layout, 'Background', 'Reactive image treatment for the current background.')
        self.bg_fit_mode_combo = QComboBox()
        self.bg_fit_mode_combo.addItem('Cover', userData='cover')
        self.bg_fit_mode_combo.addItem('Contain', userData='contain')
        self.bg_fit_mode_combo.addItem('Original', userData='original')
        self.bg_fit_mode_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_bg_fit_mode())
        widget_factory.add_form_row(bg_card, 'Fit mode', self.bg_fit_mode_combo, self.ui, apply_card_field=True)
        self.bg_user_scale_label, self.bg_user_scale_slider = widget_factory.add_slider_row(bg_card, 'Scale (100%)', 10, 400, 100, self._video_controller.update_bg_user_scale, self.ui, single_step=5)
        self.bg_edit_mode = widget_factory.add_toggle_row(bg_card, 'Edit background in preview', self._video_controller.update_bg_edit_mode, self.ui)
        row_bg_reset = QHBoxLayout()
        row_bg_reset.setContentsMargins(0, 0, 0, 0)
        row_bg_reset.setSpacing(6)
        row_bg_reset.addStretch(1)
        self.bg_reset_transform_btn = QPushButton('Reset transform')
        self._set_button_role(self.bg_reset_transform_btn, 'compactSecondary')
        self.bg_reset_transform_btn.clicked.connect(self._reset_bg_transform)
        row_bg_reset.addWidget(self.bg_reset_transform_btn)
        bg_card.addLayout(row_bg_reset)
        self.bg_brightness_label, self.bg_brightness_slider = widget_factory.add_slider_row(bg_card, 'Brightness (1.00)', 0, 200, 100, self._video_controller.update_bg_brightness, self.ui)
        self.bg_reactivity_label, self.bg_reactivity_slider = widget_factory.add_slider_row(bg_card, 'Audio Reactivity (0.00)', 0, 200, 0, self._video_controller.update_bg_reactivity, self.ui)
        self.bg_smoothing_label, self.bg_smoothing_slider = widget_factory.add_slider_row(bg_card, 'Reaction Smoothness (0.80)', 0, 99, 80, self._video_controller.update_bg_smoothing, self.ui)
        self.bg_motion_mode_combo = QComboBox()
        self.bg_motion_mode_combo.addItem('None', userData='none')
        self.bg_motion_mode_combo.addItem('Zoom', userData='zoom')
        self.bg_motion_mode_combo.addItem('Vibrate', userData='vibrate')
        self.bg_motion_mode_combo.addItem('Zoom + Vibrate', userData='both')
        self.bg_motion_mode_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_bg_motion_mode())
        widget_factory.add_form_row(bg_card, 'Motion', self.bg_motion_mode_combo, self.ui, apply_card_field=True)
        self.bg_motion_zoom_label, self.bg_motion_zoom_slider = widget_factory.add_slider_row(bg_card, 'Zoom Strength (1.00)', 0, 200, 100, self._video_controller.update_bg_motion_zoom, self.ui)
        self.bg_motion_vibrate_label, self.bg_motion_vibrate_slider = widget_factory.add_slider_row(bg_card, 'Vibrate Strength (1.00)', 0, 200, 100, self._video_controller.update_bg_motion_vibrate, self.ui)
        fx_card = section_card(bg_layout, 'Corner Effects', 'Add subtle vignette or smoky corners for a more cinematic frame.')
        self.vignette_enabled = widget_factory.add_toggle_row(fx_card, 'Enable Vignette', self._video_controller.update_vignette_enabled, self.ui)
        self.vignette_controls = QWidget()
        vc = QVBoxLayout(self.vignette_controls)
        vc.setContentsMargins(0, 0, 0, 0)
        vc.setSpacing(5)
        self.vignette_strength_label, self.vignette_strength_slider = widget_factory.add_slider_row(vc, 'Strength (0.35)', 0, 100, 35, self._video_controller.update_vignette_strength, self.ui)
        self.vignette_feather_label, self.vignette_feather_slider = widget_factory.add_slider_row(vc, 'Feather (0.65)', 0, 100, 65, self._video_controller.update_vignette_feather, self.ui)
        self.vignette_opacity_label, self.vignette_opacity_slider = widget_factory.add_slider_row(vc, 'Opacity (0.65)', 0, 100, 65, self._video_controller.update_vignette_opacity, self.ui)
        vcol_widget = QWidget()
        vcol_row = QHBoxLayout(vcol_widget)
        vcol_row.setContentsMargins(0, 0, 0, 0)
        vcol_row.setSpacing(6)
        self.vignette_color_input = QLineEdit()
        self._apply_card_field(self.vignette_color_input)
        self.vignette_color_input.textChanged.connect(lambda _: self._video_controller.update_vignette_color())
        btn_vcol = QPushButton('Pick')
        self._set_button_role(btn_vcol, 'compactSecondary')
        btn_vcol.clicked.connect(self._pick_vignette_color)
        vcol_row.addWidget(self.vignette_color_input, 1)
        vcol_row.addWidget(btn_vcol)
        widget_factory.add_form_row(vc, 'Color', vcol_widget, self.ui, apply_card_field=False)
        fx_card.addWidget(self.vignette_controls)
        self.smoke_enabled = widget_factory.add_toggle_row(fx_card, 'Enable Smoke', self._video_controller.update_smoke_enabled, self.ui)
        self.smoke_controls = QWidget()
        sc = QVBoxLayout(self.smoke_controls)
        sc.setContentsMargins(0, 0, 0, 0)
        sc.setSpacing(5)
        self.smoke_strength_label, self.smoke_strength_slider = widget_factory.add_slider_row(sc, 'Strength (0.35)', 0, 100, 35, self._video_controller.update_smoke_strength, self.ui)
        self.smoke_blur_label, self.smoke_blur_slider = widget_factory.add_slider_row(sc, 'Blur (0.55)', 0, 100, 55, self._video_controller.update_smoke_blur, self.ui)
        self.smoke_noise_label, self.smoke_noise_slider = widget_factory.add_slider_row(sc, 'Noise (0.55)', 0, 100, 55, self._video_controller.update_smoke_noise, self.ui)
        self.smoke_speed_label, self.smoke_speed_slider = widget_factory.add_slider_row(sc, 'Motion Speed (0.35)', 0, 200, 35, self._video_controller.update_smoke_speed, self.ui)
        self.smoke_opacity_label, self.smoke_opacity_slider = widget_factory.add_slider_row(sc, 'Opacity (0.55)', 0, 100, 55, self._video_controller.update_smoke_opacity, self.ui)
        scol_widget = QWidget()
        scol_row = QHBoxLayout(scol_widget)
        scol_row.setContentsMargins(0, 0, 0, 0)
        scol_row.setSpacing(6)
        self.smoke_color_input = QLineEdit()
        self._apply_card_field(self.smoke_color_input)
        self.smoke_color_input.textChanged.connect(lambda _: self._video_controller.update_smoke_color())
        btn_scol = QPushButton('Pick')
        self._set_button_role(btn_scol, 'compactSecondary')
        btn_scol.clicked.connect(self._pick_smoke_color)
        scol_row.addWidget(self.smoke_color_input, 1)
        scol_row.addWidget(btn_scol)
        widget_factory.add_form_row(sc, 'Color', scol_widget, self.ui, apply_card_field=False)
        fx_card.addWidget(self.smoke_controls)
        bg_layout.addStretch(1)
        logo_page, logo_layout = tab_body()
        logo_card = section_card(logo_layout, 'Logo', 'Shape, scale, opacity, and logo-specific audio motion.')
        self.logo_enabled = widget_factory.add_toggle_row(logo_card, 'Enable Logo', self._video_controller.update_logo_enabled, self.ui)
        self.logo_spin_enabled = widget_factory.add_toggle_row(logo_card, 'Spin (CD)', self._video_controller.update_logo_spin_enabled, self.ui)
        self.logo_spin_controls = QWidget()
        lsc = QVBoxLayout(self.logo_spin_controls)
        lsc.setContentsMargins(0, 0, 0, 0)
        lsc.setSpacing(6)
        self.logo_spin_direction_combo = QComboBox()
        self.logo_spin_direction_combo.addItem('Clockwise', userData='cw')
        self.logo_spin_direction_combo.addItem('Counter-clockwise', userData='ccw')
        self.logo_spin_direction_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_logo_spin_direction())
        widget_factory.add_form_row(lsc, 'Direction', self.logo_spin_direction_combo, self.ui, apply_card_field=True)
        self.logo_spin_speed_label, self.logo_spin_speed_slider = widget_factory.add_slider_row(lsc, 'Speed (0°/s)', 0, 720, 0, self._video_controller.update_logo_spin_speed, self.ui, single_step=10)
        logo_card.addWidget(self.logo_spin_controls)
        self.logo_controls = QWidget()
        lc = QVBoxLayout(self.logo_controls)
        lc.setContentsMargins(0, 0, 0, 0)
        lc.setSpacing(6)
        logo_file_row = QWidget()
        logo_file_row_layout = QHBoxLayout(logo_file_row)
        logo_file_row_layout.setContentsMargins(0, 0, 0, 0)
        logo_file_row_layout.setSpacing(6)
        self.logo_path_input = QLineEdit()
        self.logo_path_input.setReadOnly(True)
        self._apply_card_field(self.logo_path_input)
        btn_pick_logo = QPushButton('Select Logo')
        self._set_button_role(btn_pick_logo, 'compactSecondary')
        btn_pick_logo.clicked.connect(self.pick_logo)
        logo_file_row_layout.addWidget(self.logo_path_input, 1)
        logo_file_row_layout.addWidget(btn_pick_logo)
        widget_factory.add_form_row(lc, 'Logo File', logo_file_row, self.ui, apply_card_field=False)
        self.logo_shape_combo = QComboBox()
        self.logo_shape_combo.addItem('Circle Crop', userData='circle')
        self.logo_shape_combo.addItem('Original Image', userData='square')
        self.logo_shape_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_logo_shape())
        widget_factory.add_form_row(lc, 'Shape', self.logo_shape_combo, self.ui, apply_card_field=True)
        self.logo_size_label, self.logo_size_slider = widget_factory.add_slider_row(lc, 'Size (2 => 200)', 1, 10, 2, self._video_controller.update_logo_size, self.ui, single_step=1, page_step=1, tick_interval=1)
        self.logo_opacity_label, self.logo_opacity_slider = widget_factory.add_slider_row(lc, 'Opacity (1.00)', 0, 100, 100, self._video_controller.update_logo_opacity, self.ui)
        self.logo_reactivity_label, self.logo_reactivity_slider = widget_factory.add_slider_row(lc, 'Audio Reactivity (0.00)', 0, 200, 0, self._video_controller.update_logo_reactivity, self.ui)
        self.logo_smoothing_label, self.logo_smoothing_slider = widget_factory.add_slider_row(lc, 'Reaction Smoothness (0.75)', 0, 99, 75, self._video_controller.update_logo_smoothing, self.ui)
        logo_card.addWidget(self.logo_controls)
        logo_layout.addStretch(1)
        particles_page, particles_layout = tab_body()
        particles_card = section_card(particles_layout, 'Particles', 'Control density, motion, and visual behavior for the particle system.')
        self.particles_enabled = widget_factory.add_toggle_row(particles_card, 'Enable Particles', self._video_controller.update_particles_enabled, self.ui)
        self.particles_controls = QWidget()
        pc = QVBoxLayout(self.particles_controls)
        pc.setContentsMargins(0, 0, 0, 0)
        pc.setSpacing(5)
        subheading(pc, 'Density')
        self.p_max_label, self.p_max_slider = widget_factory.add_slider_row(pc, 'Max Count (200)', 200, 2000, 200, self._video_controller.update_particles_max, self.ui, single_step=50)
        self.p_spawn_label, self.p_spawn_slider = widget_factory.add_slider_row(pc, 'Birth Rate (100)', 100, 1000, 100, self._video_controller.update_particles_spawn, self.ui, single_step=100)
        subheading(pc, 'Motion')
        self.p_life_label, self.p_life_slider = widget_factory.add_slider_row(pc, 'Lifetime (1.60s)', 5, 1000, 160, self._video_controller.update_particles_life, self.ui)
        self.p_speed_label, self.p_speed_slider = widget_factory.add_slider_row(pc, 'Base Speed (1.0)', 10, 150, 10, self._video_controller.update_particles_speed, self.ui)
        self.p_react_label, self.p_react_slider = widget_factory.add_slider_row(pc, 'Audio Reactivity (0.10)', 10, 50, 10, self._video_controller.update_particles_reactivity, self.ui)
        self.p_smoothing_label, self.p_smoothing_slider = widget_factory.add_slider_row(pc, 'Reaction Smoothness (0.65)', 0, 99, 65, self._video_controller.update_particles_smoothing, self.ui)
        subheading(pc, 'Behavior')
        self.p_spawn_mode_combo = QComboBox()
        self.p_spawn_mode_combo.addItem('Always', userData='always')
        self.p_spawn_mode_combo.addItem('Audio Reactive Only', userData='reactiveOnly')
        self.p_spawn_mode_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_particles_spawn_mode())
        widget_factory.add_form_row(pc, 'Spawn Mode', self.p_spawn_mode_combo, self.ui, apply_card_field=True, label_min_width=120)
        self.p_spawn_trigger_combo = QComboBox()
        self.p_spawn_trigger_combo.addItem('Kick or Bass', userData='both')
        self.p_spawn_trigger_combo.addItem('Kick', userData='kick')
        self.p_spawn_trigger_combo.addItem('Bass', userData='bass')
        self.p_spawn_trigger_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_particles_spawn_trigger())
        widget_factory.add_form_row(pc, 'Spawn Trigger', self.p_spawn_trigger_combo, self.ui, apply_card_field=True, label_min_width=120)
        self.p_spawn_threshold_label, self.p_spawn_threshold_slider = widget_factory.add_slider_row(pc, 'Spawn Threshold (0.15)', 0, 100, 15, self._video_controller.update_particles_spawn_threshold, self.ui)
        subheading(pc, 'Visual')
        self.p_variant_combo = QComboBox()
        self.p_variant_combo.addItem('Classic', userData='classic')
        self.p_variant_combo.addItem('Bokeh Bubbles', userData='bokeh')
        self.p_variant_combo.addItem('Soap Bubble', userData='soap')
        self.p_variant_combo.addItem('Floating Dust', userData='dust')
        self.p_variant_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_particles_variant())
        widget_factory.add_form_row(pc, 'Bubble Mode', self.p_variant_combo, self.ui, apply_card_field=True, label_min_width=120)
        self.p_spawn_area_combo = QComboBox()
        self.p_spawn_area_combo.addItem('Center Ring', userData='centerRing')
        self.p_spawn_area_combo.addItem('Bottom', userData='bottom')
        self.p_spawn_area_combo.addItem('Edges', userData='edges')
        self.p_spawn_area_combo.addItem('Full Frame', userData='full')
        self.p_spawn_area_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_particles_spawn_area())
        widget_factory.add_form_row(pc, 'Spawn Area', self.p_spawn_area_combo, self.ui, apply_card_field=True, label_min_width=120)
        self.p_size_jitter_label, self.p_size_jitter_slider = widget_factory.add_slider_row(pc, 'Size Variance (0.00)', 0, 100, 0, self._video_controller.update_particles_size_jitter, self.ui)
        self.p_drift_label, self.p_drift_slider = widget_factory.add_slider_row(pc, 'Drift (0.00)', 0, 100, 0, self._video_controller.update_particles_drift, self.ui)
        self.p_swirl_label, self.p_swirl_slider = widget_factory.add_slider_row(pc, 'Swirl (0.00)', 0, 100, 0, self._video_controller.update_particles_swirl, self.ui)
        self.p_style_combo = QComboBox()
        self.p_style_combo.addItem('Dot', userData='dot')
        self.p_style_combo.addItem('Soft Glow', userData='glow')
        self.p_style_combo.addItem('Ring', userData='ring')
        self.p_style_combo.addItem('Spark', userData='spark')
        self.p_style_combo.addItem('Bokeh', userData='bokeh')
        self.p_style_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_particles_style())
        widget_factory.add_form_row(pc, 'Style', self.p_style_combo, self.ui, apply_card_field=True, label_min_width=120)
        self.p_size_label, self.p_size_slider = widget_factory.add_slider_row(pc, 'Particle Size (2.0)', 10, 100, 20, self._video_controller.update_particles_size, self.ui, single_step=5)
        self.p_opacity_label, self.p_opacity_slider = widget_factory.add_slider_row(pc, 'Opacity (0.35)', 0, 100, 35, self._video_controller.update_particles_opacity, self.ui)
        col_row = QHBoxLayout()
        col_row.setContentsMargins(0, 0, 0, 0)
        col_row.setSpacing(6)
        self.p_color_input = QLineEdit()
        self._apply_card_field(self.p_color_input)
        self.p_color_input.textChanged.connect(lambda _: self._video_controller.update_particles_color())
        btnc = QPushButton('Pick')
        self._set_button_role(btnc, 'compactSecondary')
        btnc.clicked.connect(self._pick_particle_color)
        col_row.addWidget(self.p_color_input, 1)
        col_row.addWidget(btnc)
        pc.addLayout(col_row)
        react_row_widget = QWidget()
        react_row = QHBoxLayout(react_row_widget)
        react_row.setContentsMargins(0, 0, 0, 0)
        react_row.setSpacing(6)
        self.p_react_color_input = QLineEdit()
        self._apply_card_field(self.p_react_color_input)
        self.p_react_color_input.textChanged.connect(lambda _: self._video_controller.update_particles_react_color())
        btnrc = QPushButton('Pick')
        self._set_button_role(btnrc, 'compactSecondary')
        btnrc.clicked.connect(self._pick_particle_react_color)
        react_row.addWidget(self.p_react_color_input, 1)
        react_row.addWidget(btnrc)
        widget_factory.add_form_row(pc, 'React Color', react_row_widget, self.ui, apply_card_field=False, label_min_width=120)
        self.p_react_strength_label, self.p_react_strength_slider = widget_factory.add_slider_row(pc, 'React Strength (0.65)', 0, 100, 65, self._video_controller.update_particles_react_strength, self.ui)
        particles_card.addWidget(self.particles_controls)
        particles_layout.addStretch(1)
        text_page, text_layout = tab_body()
        self.text_overlay_enabled = []
        self.text_overlay_controls = []
        self.text_overlay_text = []
        self.text_overlay_start = []
        self.text_overlay_duration = []
        self.text_overlay_anchor = []
        self.text_overlay_x_label = []
        self.text_overlay_x_slider = []
        self.text_overlay_y_label = []
        self.text_overlay_y_slider = []
        self.text_overlay_size_label = []
        self.text_overlay_size_slider = []
        self.text_overlay_color = []
        self.text_overlay_stroke_color = []
        self.text_overlay_stroke_label = []
        self.text_overlay_stroke_slider = []
        self.text_overlay_shadow_label = []
        self.text_overlay_shadow_slider = []
        self.text_overlay_anim = []
        for i in range(5):
            item = section_card(text_layout, f'Text {i+1}', 'Overlay text for intros, titles, or announcements.')
            enabled = widget_factory.add_toggle_row(item, 'Enable', (lambda i=i: self._video_controller.update_text_enabled(i)), self.ui)
            controls = QWidget()
            cl = QVBoxLayout(controls)
            cl.setContentsMargins(0, 0, 0, 0)
            cl.setSpacing(6)
            te = QTextEdit()
            te.setMinimumHeight(70)
            self._set_field_role(te, 'card')
            te.textChanged.connect((lambda i=i: self._video_controller.update_text_content(i)))
            widget_factory.add_form_row(cl, 'Text', te, self.ui, apply_card_field=False)
            start = QSpinBox()
            self._apply_card_field(start)
            start.setMinimum(0)
            start.setMaximum(36000)
            start.valueChanged.connect((lambda _v, i=i: self._video_controller.update_text_start(i)))
            widget_factory.add_form_row(cl, 'Start (sec)', start, self.ui, apply_card_field=False)
            dur = QSpinBox()
            self._apply_card_field(dur)
            dur.setMinimum(1)
            dur.setMaximum(36000)
            dur.valueChanged.connect((lambda _v, i=i: self._video_controller.update_text_duration(i)))
            widget_factory.add_form_row(cl, 'Duration (sec)', dur, self.ui, apply_card_field=False)
            anch = QComboBox()
            self._apply_card_field(anch)
            anch.addItem('Top Left', userData='top-left')
            anch.addItem('Top Center', userData='top-center')
            anch.addItem('Top Right', userData='top-right')
            anch.addItem('Center', userData='center')
            anch.addItem('Bottom Left', userData='bottom-left')
            anch.addItem('Bottom Center', userData='bottom-center')
            anch.addItem('Bottom Right', userData='bottom-right')
            anch.currentIndexChanged.connect((lambda _v, i=i: self._video_controller.update_text_anchor(i)))
            widget_factory.add_form_row(cl, 'Anchor', anch, self.ui, apply_card_field=True)
            xl, xs = widget_factory.add_slider_row(cl, 'X Offset (24px)', -1000, 1000, 24, (lambda v, i=i: self._video_controller.update_text_x(i, v)), self.ui)
            yl, ys = widget_factory.add_slider_row(cl, 'Y Offset (24px)', -1000, 1000, 24, (lambda v, i=i: self._video_controller.update_text_y(i, v)), self.ui)
            sl, ss = widget_factory.add_slider_row(cl, 'Font Size (46px)', 8, 320, 46, (lambda v, i=i: self._video_controller.update_text_size(i, v)), self.ui)
            col_widget = QWidget()
            col_row = QHBoxLayout(col_widget)
            col_row.setContentsMargins(0, 0, 0, 0)
            col_row.setSpacing(6)
            col = QLineEdit()
            self._apply_card_field(col)
            col.textChanged.connect((lambda _v=None, i=i: self._video_controller.update_text_color(i)))
            b1 = QPushButton('Pick')
            self._set_button_role(b1, 'compactSecondary')
            b1.clicked.connect((lambda _v=False, i=i: self._pick_text_color(i)))
            col_row.addWidget(col, 1)
            col_row.addWidget(b1)
            widget_factory.add_form_row(cl, 'Color', col_widget, self.ui, apply_card_field=False)
            scol_widget = QWidget()
            scol_row = QHBoxLayout(scol_widget)
            scol_row.setContentsMargins(0, 0, 0, 0)
            scol_row.setSpacing(6)
            scol = QLineEdit()
            self._apply_card_field(scol)
            scol.textChanged.connect((lambda _v=None, i=i: self._video_controller.update_text_stroke_color(i)))
            b2 = QPushButton('Pick')
            self._set_button_role(b2, 'compactSecondary')
            b2.clicked.connect((lambda _v=False, i=i: self._pick_text_stroke_color(i)))
            scol_row.addWidget(scol, 1)
            scol_row.addWidget(b2)
            widget_factory.add_form_row(cl, 'Stroke Color', scol_widget, self.ui, apply_card_field=False)
            swl, sws = widget_factory.add_slider_row(cl, 'Stroke Width (2.0)', 0, 120, 20, (lambda v, i=i: self._video_controller.update_text_stroke_width(i, v)), self.ui)
            shl, shs = widget_factory.add_slider_row(cl, 'Shadow (0.40)', 0, 100, 40, (lambda v, i=i: self._video_controller.update_text_shadow(i, v)), self.ui)
            anim = QComboBox()
            self._apply_card_field(anim)
            anim.addItem('Fade', userData='fade')
            anim.addItem('Slide Up', userData='slide_up')
            anim.addItem('Slide Down', userData='slide_down')
            anim.addItem('Slide Left', userData='slide_left')
            anim.addItem('Slide Right', userData='slide_right')
            anim.addItem('Pop', userData='pop')
            anim.addItem('Typewriter', userData='typewriter')
            anim.addItem('Glow Pulse', userData='glow')
            anim.addItem('Shake', userData='shake')
            anim.addItem('None', userData='none')
            anim.currentIndexChanged.connect((lambda _v, i=i: self._video_controller.update_text_animation(i)))
            widget_factory.add_form_row(cl, 'Animation', anim, self.ui, apply_card_field=True)
            item.addWidget(controls)
            self.text_overlay_enabled.append(enabled)
            self.text_overlay_controls.append(controls)
            self.text_overlay_text.append(te)
            self.text_overlay_start.append(start)
            self.text_overlay_duration.append(dur)
            self.text_overlay_anchor.append(anch)
            self.text_overlay_x_label.append(xl)
            self.text_overlay_x_slider.append(xs)
            self.text_overlay_y_label.append(yl)
            self.text_overlay_y_slider.append(ys)
            self.text_overlay_size_label.append(sl)
            self.text_overlay_size_slider.append(ss)
            self.text_overlay_color.append(col)
            self.text_overlay_stroke_color.append(scol)
            self.text_overlay_stroke_label.append(swl)
            self.text_overlay_stroke_slider.append(sws)
            self.text_overlay_shadow_label.append(shl)
            self.text_overlay_shadow_slider.append(shs)
            self.text_overlay_anim.append(anim)
        text_layout.addStretch(1)
        tabs.addTab(spectrum_page, 'Spectrum')
        tabs.addTab(background_page, 'Background')
        tabs.addTab(logo_page, 'Logo')
        tabs.addTab(particles_page, 'Particles')
        tabs.addTab(text_page, 'Text')
        left_panel.addWidget(tabs)
        self._video_controller.apply_template_to_controls()

