
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QSlider, QLabel, QPushButton,
    QFileDialog, QLineEdit, QComboBox, QProgressBar, QColorDialog,
    QScrollArea, QCheckBox, QMessageBox, QTabWidget, QListWidget,
    QListWidgetItem, QStackedWidget, QToolButton, QTextEdit, QSpinBox,
    QTableWidget, QTableWidgetItem, QHeaderView, QDateEdit, QSizePolicy
)
from PyQt6.QtCore import Qt, QSize
from PyQt6.QtGui import QIcon, QColor
from .components import SpectrumPreview, AspectRatioBox
from .resolution_presets import output_resolution_presets
from .helpers import widget_factory
from .helpers.style_helper import apply_cta_button, set_panel_role, set_widget_property

class VideoViewMixin:
    def _build_video_workspace_page(self) -> QWidget:
        page = QWidget()
        page_layout = QVBoxLayout(page)
        page_layout.setContentsMargins(0, 0, 0, 0)
        page_layout.setSpacing(0)
        layout = QHBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        page_layout.addLayout(layout, 1)
        left_panel_widget = QWidget()
        left_panel_widget.setFixedWidth(322)
        set_panel_role(left_panel_widget, 'sidebarLeft')
        left_outer = QVBoxLayout(left_panel_widget)
        left_outer.setContentsMargins(0, 0, 0, 0)
        left_outer.setSpacing(0)
        left_scroll = QScrollArea()
        left_scroll.setWidgetResizable(True)
        left_scroll.setFrameShape(QScrollArea.Shape.NoFrame)
        left_outer.addWidget(left_scroll)
        left_body = QWidget()
        left_scroll.setWidget(left_body)
        left_panel = QVBoxLayout(left_body)
        left_panel.setContentsMargins(10, 10, 10, 10)
        left_panel.setSpacing(8)
        template_box, template_layout = widget_factory.make_panel_section('Project Template', self.ui, subtitle_text='Manage the current template before styling and export.', soft=True)
        left_panel.addWidget(template_box)
        self.template_name_input = QLineEdit()
        self.template_name_input.setText(str(self.template.get('templateName', 'New Template')))
        self._apply_card_field(self.template_name_input)
        template_layout.addWidget(self.template_name_input)
        top_row = QHBoxLayout()
        top_row.setSpacing(8)
        self.btn_tpl_save = QPushButton('Save')
        self._set_button_role(self.btn_tpl_save, 'primary')
        self.btn_tpl_save.clicked.connect(self.save_template)
        top_row.addWidget(self.btn_tpl_save, 1)
        self.btn_tpl_delete = QPushButton('Delete')
        self._set_button_role(self.btn_tpl_delete, 'danger')
        self.btn_tpl_delete.clicked.connect(self.delete_current_template)
        top_row.addWidget(self.btn_tpl_delete)
        template_layout.addLayout(top_row)
        self.tpl_combo = QComboBox()
        self.tpl_combo.currentIndexChanged.connect(self._on_tpl_combo_changed)
        self._apply_card_field(self.tpl_combo)
        template_layout.addWidget(self.tpl_combo)
        self._build_settings_ui(left_panel)
        left_panel.addStretch(1)
        center_widget = QWidget()
        set_panel_role(center_widget, 'center')
        center_layout = QVBoxLayout(center_widget)
        center_layout.setContentsMargins(12, 12, 12, 12)
        center_layout.setSpacing(8)
        header = QWidget()
        header_layout = QHBoxLayout(header)
        header_layout.setContentsMargins(0, 0, 0, 0)
        header_layout.setSpacing(8)
        self.preview_title = QLabel(f"Preview: {self.template.get('templateName', 'New Template')}")
        self._set_label_role(self.preview_title, 'toolbarTitle')
        header_layout.addWidget(self.preview_title)
        header_layout.addStretch(1)
        self.video_output_resolution_combo = QComboBox()
        for label, value in output_resolution_presets():
            self.video_output_resolution_combo.addItem(label, userData=value)
        self._apply_card_field(self.video_output_resolution_combo)
        self.video_output_resolution_combo.setFixedWidth(280)
        self.video_output_resolution_combo.currentIndexChanged.connect(self._on_video_output_resolution_changed)
        header_layout.addWidget(self.video_output_resolution_combo)
        self.btn_popout = QPushButton('Live Preview')
        self._set_button_role(self.btn_popout, 'toolbar')
        self.btn_popout.clicked.connect(self._toggle_popout)
        header_layout.addWidget(self.btn_popout)
        self.btn_set_bg = QPushButton('Background')
        self._set_button_role(self.btn_set_bg, 'secondary')
        self.btn_set_bg.clicked.connect(self.pick_bg)
        header_layout.addWidget(self.btn_set_bg)
        center_layout.addWidget(header)
        self.preview = SpectrumPreview()
        self.preview.set_template(self.template)
        self.preview.position_changed.connect(self._on_preview_position_changed)
        if hasattr(self.preview, "background_transform_changed"):
            self.preview.background_transform_changed.connect(self._on_preview_background_transform_changed)
        res_text = ""
        try:
            settings = self._music_settings()
            res_text = str(settings.get("outputResolution", "")).strip() or str(settings.get("imageResolution", "")).strip()
        except Exception:
            res_text = ""
        try:
            if hasattr(self, "video_output_resolution_combo") and self.video_output_resolution_combo is not None:
                idx = self.video_output_resolution_combo.findData(res_text)
                self.video_output_resolution_combo.blockSignals(True)
                self.video_output_resolution_combo.setCurrentIndex(idx if idx >= 0 else 0)
                self.video_output_resolution_combo.blockSignals(False)
        except Exception:
            try:
                self.video_output_resolution_combo.blockSignals(False)
            except Exception:
                pass
        rw, rh = (16, 9)
        try:
            if hasattr(self, "_parse_output_resolution"):
                rw, rh = self._parse_output_resolution(res_text)
        except Exception:
            rw, rh = (16, 9)
        self.preview_box = AspectRatioBox(self.preview, int(rw), int(rh))
        center_layout.addWidget(self.preview_box, 2)
        center_layout.addSpacing(8)
        bottom = QWidget()
        bottom_layout = QVBoxLayout(bottom)
        bottom_layout.setContentsMargins(0, 0, 0, 0)
        bottom_layout.setSpacing(10)
        playback_section = QWidget()
        set_panel_role(playback_section, 'section')
        playback_section_layout = QVBoxLayout(playback_section)
        playback_section_layout.setContentsMargins(10, 8, 10, 8)
        playback_section_layout.setSpacing(4)
        playback_title = QLabel('Playback')
        self._set_label_role(playback_title, 'sectionTitle')
        playback_section_layout.addWidget(playback_title)
        audio_row = QHBoxLayout()
        audio_row.setContentsMargins(0, 0, 0, 0)
        audio_row.setSpacing(6)
        self.btn_back10 = QPushButton('Backward')
        self.btn_back10.setFixedHeight(32)
        self._set_button_role(self.btn_back10, 'transportPrimary')
        self.btn_back10.clicked.connect(lambda: self._audio_controller.seek_relative(-10.0))
        self.btn_play = QPushButton('Play')
        self.btn_play.setFixedHeight(32)
        self._set_button_role(self.btn_play, 'transportPrimary')
        self.btn_play.clicked.connect(self._audio_controller.toggle_playback)
        self.btn_stop = QPushButton('Stop')
        self.btn_stop.setFixedHeight(32)
        self._set_button_role(self.btn_stop, 'transportPrimary')
        self.btn_stop.clicked.connect(self._audio_controller.stop_audio)
        self.btn_fwd10 = QPushButton('Forward')
        self.btn_fwd10.setFixedHeight(32)
        self._set_button_role(self.btn_fwd10, 'transportPrimary')
        self.btn_fwd10.clicked.connect(lambda: self._audio_controller.seek_relative(10.0))
        audio_row.addWidget(self.btn_back10)
        audio_row.addWidget(self.btn_play)
        audio_row.addWidget(self.btn_stop)
        audio_row.addWidget(self.btn_fwd10)
        self.seek_label = QLabel('00:00 / 00:00')
        self._set_label_role(self.seek_label, 'timer')
        audio_row.addWidget(self.seek_label)
        audio_row.addStretch(1)
        playback_section_layout.addLayout(audio_row)
        self.seek_slider = QSlider(Qt.Orientation.Horizontal)
        self.seek_slider.setMinimum(0)
        self.seek_slider.setMaximum(1000)
        self.seek_slider.sliderPressed.connect(self._on_seek_pressed)
        self.seek_slider.sliderReleased.connect(self._on_seek_released)
        playback_section_layout.addWidget(self.seek_slider)
        bottom_layout.addWidget(playback_section)
        export_section = QWidget()
        set_panel_role(export_section, 'section')
        export_section_layout = QVBoxLayout(export_section)
        export_section_layout.setContentsMargins(10, 8, 10, 8)
        export_section_layout.setSpacing(6)
        export_title = QLabel('Export Queue')
        self._set_label_role(export_title, 'sectionTitle')
        export_section_layout.addWidget(export_title)
        export_columns = QHBoxLayout()
        export_columns.setContentsMargins(0, 0, 0, 0)
        export_columns.setSpacing(10)
        export_left_card = QWidget()
        set_panel_role(export_left_card, 'section')
        export_left_card_layout = QVBoxLayout(export_left_card)
        export_left_card_layout.setContentsMargins(10, 10, 10, 10)
        export_left_card_layout.setSpacing(6)
        export_left = QVBoxLayout()
        export_left.setContentsMargins(0, 0, 0, 0)
        export_left.setSpacing(4)
        track_label = QLabel('TRACK LIST')
        self._set_label_role(track_label, 'statusLabel')
        export_left.addWidget(track_label)
        self.mp3_list = QListWidget()
        self._apply_card_field(self.mp3_list)
        self._set_widget_property(self.mp3_list, 'uiRole', 'trackList')
        self.mp3_list.setSpacing(0)
        self.mp3_list.setMinimumHeight(0)
        self.mp3_list.currentRowChanged.connect(self.on_mp3_selected)
        export_left.addWidget(self.mp3_list, 1)
        export_left_card_layout.addLayout(export_left, 1)
        export_columns.addWidget(export_left_card, 1)
        export_right = QVBoxLayout()
        export_right.setContentsMargins(0, 0, 0, 0)
        export_right.setSpacing(0)
        export_info_card = QWidget()
        set_panel_role(export_info_card, 'section')
        export_info_layout = QVBoxLayout(export_info_card)
        export_info_layout.setContentsMargins(10, 10, 10, 10)
        export_info_layout.setSpacing(8)
        export_actions_title = QLabel('ACTIONS')
        self._set_label_role(export_actions_title, 'statusStrong')
        export_info_layout.addWidget(export_actions_title)
        export_top_row = QHBoxLayout()
        export_top_row.setContentsMargins(0, 0, 0, 0)
        export_top_row.setSpacing(8)
        self.btn_pick_mp3_dir = QPushButton('Select MP3 Folder')
        apply_cta_button(self.btn_pick_mp3_dir, 'primary', self.ui)
        self.btn_pick_mp3_dir.clicked.connect(self.pick_mp3_folder)
        export_top_row.addWidget(self.btn_pick_mp3_dir, 2)
        self.btn_generate_thumbnail = QPushButton('Generate Thumbnail')
        apply_cta_button(self.btn_generate_thumbnail, 'secondary', self.ui)
        self.btn_generate_thumbnail.clicked.connect(self._on_generate_thumbnail_clicked)
        export_top_row.addWidget(self.btn_generate_thumbnail, 1)
        self.btn_export_toggle = QPushButton('Export')
        apply_cta_button(self.btn_export_toggle, 'success', self.ui)
        self.btn_export_toggle.clicked.connect(self._toggle_export)
        export_top_row.addWidget(self.btn_export_toggle, 1)
        export_info_layout.addLayout(export_top_row)
        export_options_row = QHBoxLayout()
        export_options_row.setContentsMargins(0, 0, 0, 0)
        export_options_row.setSpacing(10)
        export_options_left = QVBoxLayout()
        export_options_left.setContentsMargins(0, 0, 0, 0)
        export_options_left.setSpacing(0)
        self.export_auto_merge_toggle = widget_factory.add_toggle_row(export_options_left, 'Auto merge MP4', self._on_export_auto_merge_changed, self.ui)
        export_options_row.addLayout(export_options_left, 1)
        export_options_right = QVBoxLayout()
        export_options_right.setContentsMargins(0, 0, 0, 0)
        export_options_right.setSpacing(0)
        self.export_speed_combo = QComboBox()
        self._apply_card_field(self.export_speed_combo)
        self.export_speed_combo.addItem("Balanced", "balanced")
        self.export_speed_combo.addItem("Fast", "fast")
        self.export_speed_combo.addItem("Very Fast", "very_fast")
        self.export_speed_combo.currentIndexChanged.connect(self._on_export_speed_mode_changed)
        widget_factory.add_form_row(export_options_right, "Speed", self.export_speed_combo, self.ui, apply_card_field=False, label_min_width=80)
        self.export_workers_spin = QSpinBox()
        self.export_workers_spin.setRange(1, 10)
        self.export_workers_spin.setValue(1)
        self._apply_card_field(self.export_workers_spin)
        self.export_workers_spin.valueChanged.connect(lambda v: self._on_export_workers_changed(int(v)))
        widget_factory.add_form_row(export_options_right, 'Workers', self.export_workers_spin, self.ui, apply_card_field=False, label_min_width=80)
        export_options_row.addLayout(export_options_right, 1)
        export_info_layout.addLayout(export_options_row)
        status_title = QLabel('Status')
        self._set_label_role(status_title, 'statusStrong')
        export_info_layout.addWidget(status_title)
        self.export_progress = QProgressBar()
        self.export_progress.setRange(0, 1000)
        self.export_progress.setValue(0)
        self.export_progress.setTextVisible(True)
        self.export_progress.setFormat('Overall: 0%')
        self.export_progress.setFixedHeight(18)
        set_widget_property(self.export_progress, "uiRole", "exportProgress")
        export_info_layout.addWidget(self.export_progress)
        self.export_merge_progress = QProgressBar()
        self.export_merge_progress.setRange(0, 1000)
        self.export_merge_progress.setValue(0)
        self.export_merge_progress.setTextVisible(True)
        self.export_merge_progress.setFormat('Merging: 0%')
        self.export_merge_progress.setFixedHeight(18)
        set_widget_property(self.export_merge_progress, "uiRole", "mergeProgress")
        self.export_merge_progress.setVisible(False)
        export_info_layout.addWidget(self.export_merge_progress)
        self.btn_export_merge_stop = QPushButton('Stop Merge')
        self._set_button_role(self.btn_export_merge_stop, 'warning')
        self.btn_export_merge_stop.setFixedHeight(30)
        self.btn_export_merge_stop.setVisible(False)
        self.btn_export_merge_stop.clicked.connect(self.stop_export_merge)
        export_info_layout.addWidget(self.btn_export_merge_stop)
        current_track_title = QLabel('Current Track')
        self._set_label_role(current_track_title, 'statusLabel')
        export_info_layout.addWidget(current_track_title)
        self.export_status = QLabel('')
        self._set_label_role(self.export_status, 'statusHeadline')
        export_info_layout.addWidget(self.export_status)
        detail_title = QLabel('Details')
        self._set_label_role(detail_title, 'statusLabel')
        export_info_layout.addWidget(detail_title)
        self.export_detail_label = QLabel('')
        self._set_label_role(self.export_detail_label, 'statusMuted')
        self.export_detail_label.setWordWrap(True)
        export_info_layout.addWidget(self.export_detail_label)
        output_title = QLabel('Output')
        self._set_label_role(output_title, 'statusLabel')
        export_info_layout.addWidget(output_title)
        self.export_output_label = QLabel('Output Folder: Not selected')
        self._set_label_role(self.export_output_label, 'statusMuted')
        self.export_output_label.setWordWrap(True)
        export_info_layout.addWidget(self.export_output_label)
        export_right.addWidget(export_info_card)
        export_right.addStretch(1)
        export_columns.addLayout(export_right, 1)
        export_section_layout.addLayout(export_columns, 1)
        bottom_layout.addWidget(export_section, 1)
        center_layout.addWidget(bottom, 1)
        layout.addWidget(left_panel_widget)
        layout.addWidget(center_widget, 1)
        right_panel_widget = QWidget()
        right_panel_widget.setFixedWidth(336)
        set_panel_role(right_panel_widget, 'sidebarRight')
        right_outer = QVBoxLayout(right_panel_widget)
        right_outer.setContentsMargins(0, 0, 0, 0)
        right_outer.setSpacing(0)
        right_scroll = QScrollArea()
        right_scroll.setWidgetResizable(True)
        right_scroll.setFrameShape(QScrollArea.Shape.NoFrame)
        right_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        right_scroll.setAlignment(Qt.AlignmentFlag.AlignTop)
        right_outer.addWidget(right_scroll)
        right_body = QWidget()
        right_scroll.setWidget(right_body)
        self.right_layout = QVBoxLayout(right_body)
        self.right_layout.setContentsMargins(10, 0, 10, 10)
        self.right_layout.setSpacing(4)
        self._build_layer_ui(self.right_layout)
        self._apply_phase1_ux_tuning()
        layout.addWidget(right_panel_widget)
        return page

    def _build_layer_ui(self, right_panel: QVBoxLayout):
    
        def section_box(title_text: str, subtitle_text: str='') -> QVBoxLayout:
            box, body = widget_factory.make_panel_section(title_text, self.ui, subtitle_text=subtitle_text, soft=True)
            right_panel.addWidget(box)
            return body
    
        def cb_row(layout: QVBoxLayout, label: str, on_change):
            return widget_factory.add_toggle_row(layout, label, on_change, self.ui)
        title = QLabel('Layer Inspector')
        self._set_label_role(title, 'pageTitle')
        right_panel.addWidget(title)
        layer_layout = section_box('Layer', 'Choose the active ring and edit its identity.')
        self.layer_selector = QComboBox()
        self._apply_card_field(self.layer_selector)
        self.layer_selector.currentIndexChanged.connect(self._on_layer_selector_changed)
        layer_layout.addWidget(self.layer_selector)
        layer_actions = QHBoxLayout()
        layer_actions.setContentsMargins(0, 0, 0, 0)
        layer_actions.setSpacing(4)
        self.btn_add_layer = QPushButton('Add')
        self._set_button_role(self.btn_add_layer, 'primary')
        self.btn_add_layer.clicked.connect(self._add_layer)
        layer_actions.addWidget(self.btn_add_layer, 1)
        self.btn_duplicate_layer = QPushButton('Duplicate')
        self._set_button_role(self.btn_duplicate_layer, 'secondary')
        self.btn_duplicate_layer.clicked.connect(self._duplicate_selected_layer)
        layer_actions.addWidget(self.btn_duplicate_layer, 1)
        self.btn_remove_layer = QPushButton('Delete')
        self._set_button_role(self.btn_remove_layer, 'danger')
        self.btn_remove_layer.clicked.connect(self._remove_selected_layer)
        layer_actions.addWidget(self.btn_remove_layer, 1)
        layer_layout.addLayout(layer_actions)
        self.layer_editing = QLabel('Editing: Base Ring')
        self._set_label_role(self.layer_editing, 'meta')
        layer_layout.addWidget(self.layer_editing)
        self.layer_name_input = QLineEdit()
        self.layer_name_input.textEdited.connect(lambda _: self._rename_selected_layer())
        widget_factory.add_form_row(layer_layout, 'Layer Name', self.layer_name_input, self.ui, apply_card_field=True)
        self.layer_gravity_combo = QComboBox()
        gravs = [('bottom', 'Bottom (Rabbit Ears on Top)'), ('top', 'Top'), ('left', 'Left'), ('right', 'Right')]
        for v, label in gravs:
            self.layer_gravity_combo.addItem(label, userData=v)
        self.layer_gravity_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_layer_gravity())
        widget_factory.add_form_row(layer_layout, 'Gravity', self.layer_gravity_combo, self.ui, apply_card_field=True)
        geometry_layout = section_box('Geometry', 'Shape and spacing controls for the selected ring.')
        self.layer_curved_cb = cb_row(geometry_layout, 'Curve 180', self._video_controller.update_layer_curved)
        self.layer_mirrored_cb = cb_row(geometry_layout, 'Mirror 360', self._video_controller.update_layer_mirrored)
        self.layer_fill_cb = cb_row(geometry_layout, 'Fill Circle', self._video_controller.update_layer_fill_circle)
        self.layer_barwidth_label, self.layer_barwidth_slider = widget_factory.add_slider_row(geometry_layout, 'Bar Width (4)', 1, 50, 4, self._video_controller.update_layer_bar_width, self.ui)
        self.layer_thickness_label, self.layer_thickness_slider = widget_factory.add_slider_row(geometry_layout, 'Spike Height (30)', 1, 120, 30, self._video_controller.update_layer_thickness, self.ui)
        self.layer_radius_label, self.layer_radius_slider = widget_factory.add_slider_row(geometry_layout, 'Layer Gap (0)', 0, 400, 0, self._video_controller.update_layer_radius, self.ui)
        self.layer_opacity_label, self.layer_opacity_slider = widget_factory.add_slider_row(geometry_layout, 'Opacity (1.00)', 0, 100, 100, self._video_controller.update_layer_opacity, self.ui)
        blend_layout = section_box('Blend / Glow', 'Balance compositing and halo softness.')
        self.layer_blend_combo = QComboBox()
        self.layer_blend_combo.addItem('Normal', userData='normal')
        self.layer_blend_combo.addItem('Additive', userData='add')
        self.layer_blend_combo.addItem('Screen', userData='screen')
        self.layer_blend_combo.currentIndexChanged.connect(lambda _: self._video_controller.update_layer_blend_mode())
        widget_factory.add_form_row(blend_layout, 'Blend', self.layer_blend_combo, self.ui, apply_card_field=True)
        self.layer_glow_label, self.layer_glow_slider = widget_factory.add_slider_row(blend_layout, 'Glow Strength (0)', 0, 100, 0, self._video_controller.update_layer_glow, self.ui)
        self.layer_blur_label, self.layer_blur_slider = widget_factory.add_slider_row(blend_layout, 'Glow Softness (0)', 0, 30, 0, self._video_controller.update_layer_blur, self.ui)
        color_layout = section_box('Color Engine', 'Pick solid or gradient color behavior.')
        self.layer_color_mode = QComboBox()
        self.layer_color_mode.addItem('Solid Color', userData='solid')
        self.layer_color_mode.addItem('Gradient', userData='gradient')
        self.layer_color_mode.currentIndexChanged.connect(lambda _: self._video_controller.update_layer_color_mode())
        widget_factory.add_form_row(color_layout, 'Mode', self.layer_color_mode, self.ui, apply_card_field=True)
        self.layer_solid_widget = QWidget()
        sl = QVBoxLayout(self.layer_solid_widget)
        sl.setContentsMargins(0, 0, 0, 0)
        sl.setSpacing(3)
        self.layer_solid_input = QLineEdit()
        self.layer_solid_input.textChanged.connect(lambda _: self._video_controller.update_layer_solid_color_text())
        color_field_row = QHBoxLayout()
        color_field_row.setContentsMargins(0, 0, 0, 0)
        color_field_row.setSpacing(6)
        color_label = QLabel('Color')
        self._set_label_role(color_label, 'metricTitle')
        color_label.setMinimumWidth(80)
        color_field_row.addWidget(color_label)
        self._apply_card_field(self.layer_solid_input)
        color_field_row.addWidget(self.layer_solid_input, 1)
        bs = QPushButton('Pick')
        self._set_button_role(bs, 'compactSecondary')
        bs.clicked.connect(self._pick_layer_solid_color)
        color_field_row.addWidget(bs)
        sl.addLayout(color_field_row)
        color_layout.addWidget(self.layer_solid_widget)
        self.layer_grad_widget = QWidget()
        gl = QVBoxLayout(self.layer_grad_widget)
        gl.setContentsMargins(0, 0, 0, 0)
        gl.setSpacing(5)
        self.layer_grad_dir = QComboBox()
        dirs = [('left-to-right', 'Left to Right'), ('top-to-bottom', 'Top to Bottom'), ('diagonal', 'Diagonal'), ('radial', 'Radial'), ('circular', 'Circular')]
        for v, label in dirs:
            self.layer_grad_dir.addItem(label, userData=v)
        self.layer_grad_dir.currentIndexChanged.connect(lambda _: self._video_controller.update_layer_grad_dir())
        widget_factory.add_form_row(gl, 'Direction', self.layer_grad_dir, self.ui, apply_card_field=True)
        self.layer_grad_preset = QComboBox()
        presets = [('#ff00ff,#00ffff', 'Cyber Blue'), ('#ff8800,#ff0000', 'EDM Fire'), ('#00ff00,#ffff00', 'Toxic'), ('#8a2be2,#4b0082', 'Galaxy'), ('#00ffff,#ffffff', 'Ice'), ('#ff4500,#ff1493', 'Lava'), ('#ff8c00,#ff69b4', 'Sunset'), ('#ff0000,#00ff00,#0000ff', 'RGB Flow')]
        for v, label in presets:
            self.layer_grad_preset.addItem(label, userData=v)
        self.layer_grad_preset.currentIndexChanged.connect(lambda _: self._video_controller.update_layer_grad_preset())
        widget_factory.add_form_row(gl, 'Preset', self.layer_grad_preset, self.ui, apply_card_field=True)
        color_layout.addWidget(self.layer_grad_widget)
        right_panel.addStretch(1)
        self._video_controller.apply_template_to_controls()

